version: '3.8'

services:
  weather:
    build: ./service-weather
    image: boxb/weather
    restart: unless-stopped
    container_name: weather
    environment:
      - PORT=3000
      - MISSION_HOST=mission
      - MISSION_PORT=3002
    volumes:
      - ./service-weather/src/:/app/src/
    depends_on:
      - mongo
    expose:
      - "3000"
    ports:
      - 3000:3000
    networks:
      - services
      - proxy

  metrics:
    build: ./service-module-metrics
    image: boxb/module-metrics
    restart: unless-stopped
    container_name: module-metrics
    environment:
      - PORT=3003
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=blue_origin
    depends_on:
      - mongo
    expose:
      - "3003"
    ports:
      - 3003:3003
    networks:
      - services
      - proxy

  actions:
    build: ./service-module-actions
    image: boxb/module-actions
    restart: unless-stopped
    container_name: module-actions
    environment:
      - PORT=3005
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=blue_origin
    depends_on:
      - mongo
    expose:
      - "3005"
    ports:
      - 3005:3005
    networks:
      - services
      - proxy

  telemetry-sender:
    build: ./service-telemetry-sender
    image: boxb/telemetry-sender
    restart: unless-stopped
    container_name: telemetrysender
    environment:
      - PORT=3004
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=blue_origin
    volumes:
      - ./service-telemetry-sender/src/:/app/src/
    depends_on:
      - mongo
    expose:
      - "3004"
    ports:
      - 3004:3004
    networks:
      - services
      - proxy

  rocket:
    build: ./service-rocket
    image: boxb/rocket
    restart: unless-stopped
    container_name: rocket
    environment:
      - PORT=3001
      - SOCKET_PORT=30011
      - MISSION_HOST=mission
      - MISSION_PORT=3002
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=blue_origin
    volumes:
      - ./service-rocket/src/:/app/src/
    depends_on:
      - mongo
    expose:
      - "3001"
    ports:
      - 3001:3001
    networks:
      - services
      - proxy

  mission:
    build: ./service-mission
    image: boxb/mission
    container_name: mission
    restart: unless-stopped
    environment:
      - PORT=3002
      - ROCKET_HOST=rocket
      - ROCKET_PORT=3001
      - WEATHER_HOST=weather
      - WEATHER_PORT=3000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=blue_origin
    volumes:
      - ./service-mission/src/:/app/src/
    depends_on:
      - mongo
    expose:
      - "3002"
    ports:
      - 3002:3002
    networks:
      - services
      - proxy

  mongo:
    image: mongo:latest
    container_name: boxb-mongo
    restart: unless-stopped
    environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: toor
      - MONGODB_DATABASE="blue_origin"
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - services

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./reverse_proxy.conf:/etc/nginx/nginx.conf
    networks:
      - proxy
    ports:
      - 80:80
    depends_on:
      - mongo
      - rocket
      - mission
      - weather
      - metrics
      - telemetry-sender

networks:
  services:
  proxy:

