version: '3.8'

services:
  weather:
    build: ./service-weather
    restart: unless-stopped
    container_name: weather
    environment:
      - PORT=3000
      - MISSION_HOST=mission
      - MISSION_PORT=3002
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=nest
    volumes:
      - ./service-weather/src/:/app/src/
    depends_on:
      - nginx
      - mongo
    expose:
      - "3000"
    ports:
      - 3000:3000
    networks:
      - services
      - proxy

  telemetry:
    build: ./service-telemetry
    restart: unless-stopped
    container_name: telemetry
    environment:
      - PORT=3003
      - ROCKET_HOST=rocket
      - ROCKET_PORT=3001
      - ROCKET_SOCKET_PORT=30011
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=nest
    volumes:
      - ./service-telemetry/src/:/app/src/
    depends_on:
      - nginx
      - mongo
    expose:
      - "3003"
    ports:
      - 3003:3003
    networks:
      - services
      - proxy

  rocket:
    build: ./service-rocket
    restart: unless-stopped
    container_name: rocket
    environment:
      - PORT=3001
      - SOCKET_PORT=30011
      - MISSION_HOST=mission
      - MISSION_PORT=3002
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=nest
    volumes:
      - ./service-rocket/src/:/app/src/
    depends_on:
      - nginx
      - mongo
    expose:
      - "3001"
    ports:
      - 3001:3001
    networks:
      - services
      - proxy

  mission:
    build: ./service-mission
    container_name: mission
    restart: unless-stopped
    environment:
      - PORT=3002
      - ROCKET_HOST=rocket
      - ROCKET_PORT=3001
      - WEATHER_HOST=weather
      - WEATHER_PORT=3000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=nest
    volumes:
      - ./service-mission/src/:/app/src/
    depends_on:
      - nginx
      - mongo
    expose:
      - "3002"
    ports:
      - 3002:3002
    networks:
      - services
      - proxy

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: toor
      - MONGODB_DATABASE="nest"
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - services

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./reverse_proxy.conf:/etc/nginx/nginx.conf
    networks:
      - proxy
    ports:
      - 80:80

networks:
  services:
  proxy:

