version: '3.8'

services:
  weather:
    build: ./service-weather
    restart: unless-stopped
    container_name: weather
    environment:
      - PORT=3000

      - ROCKET_HOST=rocket
      - ROCKET_PORT=3001

      - MISSION_HOST=mission
      - MISSION_PORT=3002

      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=nest
    expose:
      - "3000"
    ports:
      - 3000:3000
    networks:
      - services

  rocket:
    build: ./service-rocket
    restart: unless-stopped
    container_name: rocket
    environment:
      - PORT=3001

      - MISSION_HOST=mission
      - MISSION_PORT=3002

      - WEATHER_HOST=weather
      - WEATHER_PORT=3000
    expose:
      - "3001"
    ports:
      - 3001:3001
    networks:
      - services

  mission:
    build: ./service-mission
    container_name: mission
    restart: unless-stopped
    environment:
      - PORT=3002

      - ROCKET_HOST=rocket
      - ROCKET_PORT=3001

      - WEATHER_HOST=weather
      - WEATHER_PORT=3000

      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=nest
    expose:
      - "3002"
    ports:
      - 3002:3002
    networks:
      - services

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: toor
      - MONGODB_DATABASE="nest"
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - services

networks:
  services:
