version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  jest:
    docker:
        - image : cimg/ruby:2.7.1-node
    steps:
      - checkout
      - run:
          name: "Npm install and test"
          command: |
            cd ./service-mission
            ls -l
            npm install
            npm run test
            
workflows:
  version : 2
  mission_service_tests:
    jobs:
      - jest
