version: 2.1
orbs:
  node: circleci/node@3.0.0
build:
    working_directory: ~/service-mission
jobs:
  jest:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
workflows:
  mission_service_tests:
    jobs:
      - jest
