server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: module-events
    static_configs:
      - targets:
          - module-events
        labels:
          job: module-events
          __path__: /etc/event-mock.json


  - job_name: grafana
    static_configs:
      - targets:
        - grafana
        labels:
          job: grafana
          __path__: /var/grafanalog/logs.log
