# Deploy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: boxb-kafka
  name: kafka-broker0
spec:
  replicas: 1
  selector:
    matchLabels:
        app: boxb-kafka
        id: "0"
  template:
    metadata:
      labels:
        app: boxb-kafka
        id: "0"
    spec:
      containers:
      - name: boxb-kafka
        image: wurstmeister/kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-service
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_CREATE_TOPICS
          value: "topic-poll:1:1,topic-poll-response:1:1,topic-rocket-event:1:1,topic-launch-event:1:1,topic-launch-order:1:1"

---

# Service
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: boxb-kafka
spec:
  ports:
    - port: 9092
      name: kafka-port
      protocol: TCP
  selector:
    app: boxb-kafka
    id: "0"
  type: LoadBalancer



#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  labels:
#    app: kafka
#    boxb: boxb-ground
#  name: kafka
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: kafka
#      boxb: boxb-ground
#  template:
#    metadata:
#      labels:
#        app: kafka
#        boxb: boxb-ground
#    spec:
#      containers:
#      - image: wurstmeister/kafka:latest
#        name: kafka
#        imagePullPolicy: IfNotPresent
#        env:
#          - name: KAFKA_ADVERTISED_HOST_NAME
#            value: "kafka"
#          - name: KAFKA_ADVERTISED_PORT
#            value: "9092"
#          - name: KAFKA_ZOOKEEPER_CONNECT
#            value: "boxb-zookeeper:2181"
#          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
#            value: "1"
#          - name: KAFKA_BROKER_ID
#            value: "1"
#          - name: KAFKA_CREATE_TOPICS
#            value: "topic-poll:1:1,topic-poll-response:1:1,topic-rocket-event:1:1,topic-launch-event:1:1,topic-launch-order:1:1"


#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    app: kafka
#  name: kafka
#spec:
#  ports:
#  - port: 9092
#    protocol: TCP
#    targetPort: 9092
#  selector:
#    app: kafka
#  type: NodePort # Uncomment if doesnt match IP