# Deploy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
    boxb: boxb-ground
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      boxb: boxb-ground
  template:
    metadata:
      labels:
        app: mongo
        boxb: boxb-ground
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
        readinessProbe:
          exec:
            command:
              - mongo
              - --eval
              - db.adminCommand('ping')
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        env:
          - name: MONGODB_DATABASE
            value: "blue_origin"
          - name: MONGO_HOST
            value: "mongo"

---

# Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  ports:
    - port: 27017
      protocol: TCP
      name: mongo-port
  selector:
    app: mongo
  type: LoadBalancer
#  type: NodePort # Uncomment if doesnt match IP
