{
 "title": "Module Metrics 2",
 "time": { "from": "now-35s", "to": "now" },
 "refresh": "500ms",
 "panels": [
  {
   "title": "Alerts",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"module-metrics2\"}",
     "labelSelector": "*",
     "legendFormat": "Alerts",
     "target": "Query",
     "type": "table"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Kmh" }
   ],
   "targets": [
    {
     "expr": "boxb_module_metrics_speed{job=\"module-metrics2\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "LY" }
   ],
   "targets": [
    {
     "expr": "boxb_module_metrics_altitude{job=\"module-metrics2\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Fuel",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boxb_module_metrics_fuel{job=\"module-metrics2\"}",
     "legendFormat": "Fuel"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "boxb_module_metrics_latitude{job=\"module-metrics2\"}",
     "legendFormat": "Lat"
    },
    {
     "expr": "boxb_module_metrics_longitude{job=\"module-metrics2\"}",
     "legendFormat": "Lng"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boxb_module_metrics_pressure{job=\"module-metrics2\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}