{
 "title": "Module Metrics",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Kmh" }
   ],
   "targets": [
    { "expr": "boxb_module_metrics_speed", "legendFormat": "Speed" }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "boxb_module_metrics_pressure", "legendFormat": "Pressure" }
   ]
  },
  {
   "title": "Altitude",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "LY" }
   ],
   "targets": [
    { "expr": "boxb_module_metrics_altitude", "legendFormat": "Altitude" }
   ]
  },
  {
   "title": "Fuel",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "boxb_module_metrics_fuel", "legendFormat": "Fuel" }
   ]
  },
  {
   "title": "Location",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "boxb_module_metrics_latitude", "legendFormat": "Latitude" },
    { "expr": "boxb_module_metrics_longitude", "legendFormat": "Longitude" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "boxb_module_metrics_latitude", "legendFormat": "Lat" },
    { "expr": "boxb_module_metrics_longitude", "legendFormat": "Lng" }
   ]
  }
 ]
}