apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: true
    jsonData:
      timeInterval: '1s'
      
  - name: Prometheus AlertManager
    type: camptocamp-prometheus-alertmanager-datasource
    access: proxy
    url: http://alertmanager:9093
    editable: true